### ISSUE TITLE
Clear screen on rebuild

### ISSUE THREAD

**Issue by krhubert** [cosmtrek/air#139]
Hi,

Do you plan to add a clear screen option? Or maybe you accept PR with such functionality?

It might look like:
```toml
[screen]
# clear screen on each rebuild
clear_on_rebuild = true
```
