### ISSUE TITLE
Application is not being reload

### ISSUE THREAD

**Issue by sujit-baniya** [cosmtrek/air#141]
I'm trying to run app but on change it's not reloading

https://storyxpress.co/video/kld85zl4v0vjx5bls

I can't find the reason or place to debug.

**Comment by kiketordera** [comment]
I have exactly the same problem, does not matter which file I change, It does not reload...

**Comment by sujit-baniya** [comment]
@kiketordera I figured why app is not reloading.

Reason: we put a single folder in include field. That just ask air to watch files for that folder only. I see you're also using same

https://github.com/kiketordera/advanced-performance/blob/main/.air.conf#L21

Try to make it empty and it should work

**Comment by kiketordera** [comment]
@sujit-baniya thank you very much for your feedback!

Unfortunately does not work. I tried with:

include_dir = []

I also tried with
include_dir = ["/media/css", "media/css", "."]

and also one by one, nothing works for getting the hot reload to work. I am following the exact instructions that are written in the readme.md file to run it, I an not having any luck with it. I was able to develop a makefile for reloading Go code whenever Go code is changed, but my real goal is to reload the browser every time an HTML or CSS file changes.

**Comment by sujit-baniya** [comment]
@kiketordera  For me this is working fine:

.air.toml
```toml
# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./tmp/main ."
# Binary file yields from `cmd`.
bin = "tmp/main"
# Customize binary.
full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "env", "yaml"]
# Ignore these filename extensions or directories.
exclude_dir = ["assets", "tmp", "vendor", "node_modules", "build"]
# Watch these directories if you specified.
include_dir = []
# Exclude files.
exclude_file = []
# Exclude unchanged files.
exclude_unchanged = true
# This log file places in your tmp_dir.
log = "air.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false
# Delay after sending Interrupt signal
kill_delay = 500 # ms

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
```
