### ISSUE TITLE
Exclude Dir not working

### ISSUE THREAD

**Issue by JovanShandro** [cosmtrek/air#152]
Hi. I am using the following config file:

```toml
# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "." 
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./tmp/main ."
# Binary file yields from `cmd`.
bin = "./tmp/main"
# Customize binary.
full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
# Watch these filename extensions.
include_ext = []
# Ignore these filename extensions or directories.
exclude_dir = ["tmp", "agents"]
# Watch these directories if you specified.
include_dir = []
# Exclude files.
exclude_file = []
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop to run old binary when build errors occur.
stop_on_error = true
# This log file places in your tmp_dir.
log = "air_errors.log"

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

```

I have an agents folder which has a lot of files inside, and for that reason I want to exclude it. 
However when I run the air command I get these logs:

```
watching agents                                                                                               
watching agents/...                                                                  
watching agents/.../...
...  and so on   
```

Any ideas on why this could be happening?
Thank you!
