### ISSUE TITLE
Fails to see changes in file share mode ubuntu > ubuntu

### ISSUE THREAD

**Issue by khanakia** [cosmtrek/air#272]
Hi, 

I have a project folder that is shared to another ubuntu and `air` is unable to detect file changes.

Some Reference: https://github.com/remy/nodemon/issues/74

Note: I tried building with nodemon and it works `nodemon -L`

Can `air` has the same functionality ?

**Comment by khanakia** [comment]
Any update ?

**Comment by khanakia** [comment]
@borosr Do you have any idea to make it work on shared network folder ?

**Comment by borosr** [comment]
Hey, I tried to simulate the shared folder watching with docker and volumes, I don't know if this is your scenario, but here is my configs and the result I found.

You can try it by copy and paste my config into your local directory. You need four files: 
- docker-compose.yaml - for the test infrastructure
- change.sh - to simulate the change in the shared directory
- main.go - to have something what air can build
- .air.toml - this is the config file of air, I changed it in two places, added txt to include_ext and changed follow_symlink to true

# Run:
`docker-compose up`

# My conclusion:
If you haven't tried to set `follow_symlink` to `true`, maybe this was the error in your scenario, but this is just a theory.

# Snippets:
docker-compose.yaml
```yaml
version: '3.8'
services:
  ubuntu:
    image: ubuntu:latest
    working_dir: /app
    volumes:
      - .:/app/
      - shared-data:/app/shared
    command: 
      - bash 
      - -c 
      - |
        apt update -y
        apt install -y curl golang
        go mod init test
        air init
        curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | bash -s
        ./bin/air
  other_service:
    image: ubuntu:latest
    working_dir: /app
    depends_on: 
      - ubuntu
    entrypoint: /bin/bash
    command: /change.sh
    volumes:
      - shared-data:/app/shared
      - $PWD/change.sh:/change.sh

volumes:
  shared-data:
```

change.sh
```sh
#!/bin/bash

sleep 10
echo "starting..." 
for ((i=1;i<=100;i++))
do 
echo -e "$i added" >> /app/shared/file.txt
sleep $i
done
```

main.go
```go
package main

import "time"

func main() {
	println(time.Now().UTC().Format(time.RFC3339), "hello world")
}
```

.air.toml
```toml
[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = true
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "txt"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
```
