### ISSUE TITLE
Feature Request: config that runs a command (instead of a binary) after building is done.

### ISSUE THREAD

**Issue by Ghibranalj** [cosmtrek/air#277]
I wanted to make air toml that runs `make run` after `make all` with air and makefile.

my air.toml look something like this
```toml
root = "."
[build]
cmd="make all && echo DONE"
include_ext = ["c", "h", "png", "tmx"]
exclude_dir = ["objs", "docs", "deps", ".vscode", "github"]
```

I tried changin the bin to `/usr/bin/make` and the args to be `run`. but air seems to be unable to run that command.

It would be nice to have a config that executes a command after the build is done.
call it something `cmd-after` that replaces running the `bin` file.

Note: i cant run my project as an executable because its a webassembly project. I need to serve it with, in my case, python (`python -m http.server 8080`)
