### ISSUE TITLE
Question: Use environment variable in cmd

### ISSUE THREAD

**Issue by Breigner01** [cosmtrek/air#312]
Is there a way to do something like:
```toml
cmd = "go build -ldflags '-X github.com/CIDgravity/CIDgravity/backend/controller.version=${GIT_REVISION}' -o cidgravity-backend ."
```
and use the environment variable GIT_REVISION instead of GIT_REVISION as a string?

**Comment by h3n4l** [comment]
Hi @Breigner01 , there is an example to use the environment variable in [Bytebase](https://github.com/bytebase/bytebase):
[`-X 'github.com/bytebase/bytebase/bin/server/cmd.goversion=$(go version)'`](https://sourcegraph.com/github.com/bytebase/bytebase/-/blob/scripts/.air.toml?L10)

**Comment by Breigner01** [comment]
Ok so I'm actually trying to implement that, but I'm having the following error:
```
usage: link [options] main.o
```
I didn't include the whole help printed bellow because that and I don't think that it's linked but I can provide anything you think might be related

**Comment by h3n4l** [comment]
Could you paste the full output of it if there are no sensitive data?

**Comment by h3n4l** [comment]
Could you paste the file content of `.air.toml`?

**Comment by h3n4l** [comment]
Try use:
```toml
root = "."
testdata_dir = "testdata"
tmp_dir = "/tmp"

[build]
  args_bin = []
  bin = "./cidgravity-backend"
  cmd = "go build -ldflags '-X github.com/CIDgravity/CIDgravity/backend/controller.version=$(git rev-parse HEAD --short)' -o ./cidgravity-backend"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "extern", "database/liquibase"]
  exclude_file = ["config.toml.sample", "Makefile"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "toml"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
```
One more thing, can you use `go build -ldflags '-X github.com/CIDgravity/CIDgravity/backend/controller.version=$(git rev-parse HEAD --short)' -o ./cidgravity-backend` to build successfully on your local?

**Comment by Breigner01** [comment]
It does work running off of the Makefile we wrote but it doesn't when I directly run it in my shell, like wtf.
I'm running the latest version of go which is 1.18.4.
And obviously air fails with the same error as go build does in my shell

**Comment by h3n4l** [comment]
Yeah, I found that air uses [`exec.Command("/bin/sh", args...)`](https://sourcegraph.com/github.com/cosmtrek/air/-/blob/runner/util_darwin.go?L29) to build go program. 
So the final(maybe) target is to fix the build command so that you can build it successfully in your shell.

**Comment by Breigner01** [comment]
Okay well I'll have to find that.
I suspect go 1.18.4 causing this but I'm not sure, but since I update my system everyday and it kinda happened after an update it propably is the cause, so as my final goal is to mainly use air in a container (with volumes and stuff so that hot reload makes sense), I'll try using go 1.18.3

**Comment by h3n4l** [comment]
Using air in a container is a good idea! 🤩
I am curious about why that command can run successfully with Makefile : \

**Comment by Breigner01** [comment]
I'm really curious too, there is a slight difference which is using an environment variable in the Makefile instead of the command but I don't see why it would be an issue

**Comment by h3n4l** [comment]
I think so.
But follow the [**go document**](https://pkg.go.dev/cmd/go#hdr-Compile_packages_and_dependencies)
> go build [-o output] [build flags] [packages]

It seems to point out that we lose `packages` parameters.

**Comment by h3n4l** [comment]
This issue can be closed because we had solved the problem mentioned in title "Use environment variable in cmd".
cc @xiantang

**Comment by xiantang** [comment]
thx

**Comment by Breigner01** [comment]
Hey @h3n4l ,

After multiple tries, I realized that the issue is the command in `'-X github.com/CIDgravity/CIDgravity/backend/controller.version=$(git rev-parse HEAD --short)'` I don't know why but I managed to narrow it down and putting text instead of that works.
But still I'd like being able to use and environment variable instead because it would be much easier, so if you have any solution to give me, I'd be happy to try.

Thanks for the help so far.

**Comment by dyavuz** [comment]
I know this is a closed issue; but if anyone has the same problem, wrapping `-ldflags` value with escaped double quotes instead of single quotes should fix the issue.

```toml
[build]
  cmd = "go build -ldflags \"-X github.com/CIDgravity/CIDgravity/backend/controller.version=$(git rev-parse HEAD --short)\" -o ./cidgravity-backend"
```
