### ISSUE TITLE
Bug: Adding entries to `include_dir` excludes directories

### ISSUE THREAD

**Issue by soypat** [cosmtrek/air#313]
I'm working on https://github.com/soypat/upsya and am unable to use `air` due to this bug.

## Steps to reproduce
My `.air.toml` looks like (click Details)

<details>

```toml
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["-evalglob=testdata/evaluations/*/*.py"]
  bin = ";PYTHON3=python3 ./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "py"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
```

</details>

air shows the following with the above config:
```
watching .
!exclude assets
watching evaluations
watching templates
!exclude testdata
!exclude tmp
building...
running..
```
I change `include_dir` to be
```toml
  include_dir = ["testdata"]
```

## What I expected
The same message but with `watching testdata` instead of excluding.

## What I saw

Then air excludes folders which are irrelevant to the directive provided, which should be included since they contain `.tmpl` files
```
!exclude assets
!exclude evaluations
!exclude templates
!exclude testdata
!exclude tmp
building...
running...
```
