### ISSUE TITLE
Air not detecting changes source files

### ISSUE THREAD

**Issue by AdrianCarreno** [cosmtrek/air#359]
I am using Docker v4.13.1 on Windows 10, and I have a simple project, with the following structure:
```
└── Docker-go
    ├── .air.toml
    ├── docker-compose.yml
    ├── Dockerfile
    ├── go.mod
    └── main.go
```

And the contents of each file:
- `.air.toml`: as default
- `docker-compose.yml`:
  ```yaml
  version: '3.8'
    services:
      server:
        build:
          context: .
            dockerfile: Dockerfile
          ports:
            - 8080:8080
          volumes:
            - ./:/app
  ```
- `Dockerfile`:
  ```dockerfile
  FROM golang:1.19-alpine
  WORKDIR /app
  RUN go install github.com/cosmtrek/air@latest
  COPY go.* ./
  RUN go mod download
  CMD ["air", "-c", ".air.toml"]
  ```
- `go.mod`:
  ```
  module github.com/AdrianCarreno/Docker-go
  go 1.19
  require ()
  ```
- `main.go`:
  ```go
  package main

  import (
    "fmt"
    "net/http"
  )

  func main() {
    http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
      fmt.Fprintf(w, "Hello World!!!")
    })
    http.ListenAndServe(":8080", nil)
  }
  ```

When I do `docker-compose up` it builds and runs the app without a problem, but nothing happens upon changing something in `main.go`. If I make a change and save, the changes are not shown until I stop the container and run it again (without needing to rebuild).

What am I doing wrong?
