### ISSUE TITLE
Only build, do not run

### ISSUE THREAD

**Issue by sathishvj** [cosmtrek/air#365]
Is there a way to only do a build and not run the code?

  #bin = "./tmp/main"
  #bin = ""

I tried commenting out the bin line, making it empty, and even removing it.  But it still runs the program when build succeeds.

**Comment by Baliedge** [comment]
Try:

```toml
[build]
  bin = "/usr/bin/make"
  cmd = "/usr/bin/true"
```
