### ISSUE TITLE
On Windows, application output on stderr not printing immediately; instead prints after app exits

### ISSUE THREAD

**Issue by shunf4** [cosmtrek/air#412]
main.go:
```go
package main

import (
        "log"
        "time"
)

func main() {
        log.Printf("abc")
        time.Sleep(3 * time.Second)
}
```

.air.toml:
```toml
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "tmp\\main.exe"
  cmd = "go build -o ./tmp/main.exe ."
  delay = 0
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
```

### Current Behaviour
Running `air`, `2023/04/13 23:54:26 abc` does *not* get printed. Only after hitting `Ctrl-C` does the log line show.

### Expected Behaviour
Log lines on stderr get printed immediately as `log.Printf(...)` is called, just as when running the application without `air`.
