### ISSUE TITLE
Air and DLV

### ISSUE THREAD

**Issue by Notaduck** [cosmtrek/air#468]
I'm not exactly sure what the cause of this error is, but it works just fine for `@v1.40.4` but everything above that will yield the following error: 

```docker
fitter-go       | go: downloading github.com/gorilla/mux v1.8.0
fitter-go       | go: downloading github.com/lib/pq v1.10.9
fitter-go       | go: downloading github.com/tormoder/fit v0.14.0
fitter-go       | running...
fitter-go       | Error: unknown flag: --config
fitter-go       | Usage:
fitter-go       |   dlv exec <path/to/binary> [flags]
```

```toml
# Working directory
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -gcflags='all=-N -l' -o ./tmp/main ."

# Binary file yields from `cmd`.
bin = "tmp/main"

# Customize binary.
full_bin = "dlv exec /app/tmp/main --listen=:2345 --headless=true --log=true --log-output=debugger,debuglineerr,gdbwire,lldbout,rpc --accept-multiclient --api-version=2 "

# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html"]
```
