### ISSUE TITLE
Add `-p` flag to `mkdir`, when creating temp folder

### ISSUE THREAD

**Issue by ColdFire87** [cosmtrek/air#493]
Allow Air to create nested subdirs for the binaries.

Config:

```toml
root = "../../../../"
testdata_dir = "testdata"
tmp_dir = "temp/livereload"
```

![image](https://github.com/cosmtrek/air/assets/14059086/715afe2a-1d77-499a-9f31-713696a0f909)
