### ISSUE TITLE
Example of using Air with Docker Compose

### ISSUE THREAD

**Issue by dtrinh100** [cosmtrek/air#54]
Is it possible to get an example with getting Air to work with Docker Compose? It keeps giving me an error in which the Air command is not found.

**Comment by jacorpski** [comment]
Have you remembered to run `go get ...` inside the Dockerfile? If the `air` command could not be found it sounds to me that the package haven't been downloaded.

I put together a quick working example and here is my Dockerfile and docker-compose.yml:

Dockerfile
```
FROM golang:1.14

WORKDIR /usr/app

COPY . .

RUN go mod download

RUN go get github.com/cosmtrek/air
```

docker-compose.yml
```
version: '2'

services: 
  app:
    build: .
    volumes: 
      - ./:/usr/app
    command: air
```
