### ISSUE TITLE
include_file also needs include_ext to work

### ISSUE THREAD

**Issue by leandergangso** [cosmtrek/air#545]
i have the following set:

```toml
include_ext = ["go"]
include_file = ["myfile.txt"]
```

air do list out `myfeil.txt` when i'm starting air as watching, but will not rebuild when i change it.
only if i also include "txt" in include_ext array does it work as expected.
